extend = "../scripts/cargo-helpers.toml"

[tasks.all]
workspace = false
dependencies = [ "logic", "graphics" ]

[tasks.logic]
workspace = false
env = { STACK_SIZE = "134217728" }
script = [
  "cargo make crate-build wasm-logic",
  "cargo make wasm logic",
  "cargo make disassemble logic"
]

[tasks.graphics]
workspace = false
env = { STACK_SIZE = "4194304" }
script = [
  "cargo make crate-build wasm-graphics",
  "cargo make wasm graphics",
  "cargo make disassemble graphics"
]

[tasks.crate-build]
workspace = false
command = "cargo"
condition = { env_set = [ "STACK_SIZE" ] }
env = { "RUSTFLAGS" = "-Clink-arg=--stack-first -Clink-arg=--no-entry -Clink-arg=--allow-undefined -Clink-arg=--strip-all -Clink-arg=--export-dynamic -Clink-arg=--import-memory -Clink-arg=--shared-memory -Clink-arg=--max-memory=1073741824 -Clink-arg=--threads -Clink-arg=-zstack-size=${STACK_SIZE} -Clink-arg=--export=__wasm_init_memory -Clink-arg=--no-check-features -Clink-arg=--export=__wasm_init_tls -Clink-arg=--export=__tls_size -Ctarget-feature=+atomics,+bulk-memory" }
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "rask-${@}", "--target", "wasm32-unknown-unknown" ]

[tasks.wasm]
workspace = false
script = [
'''
#!/usr/bin/env bash -e
top=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ]; then
  echo "Not in a git repo!"
  exit 1
fi
file=$top/target/wasm32-unknown-unknown/${BUILD_ENV}/rask_wasm_${@}.wasm
wasm-bindgen $file --out-dir $top/client/gen \
  --no-typescript \
  --target no-modules \
  --remove-producers-section \
  --remove-name-section \
  --no-demangle
wasm-opt $top/client/gen/rask_wasm_${@}_bg.wasm \
  --memory-packing --remove-unused-brs --enable-mutable-globals --enable-threads -Oz --enable-bulk-memory \
  -o $top/client/gen/${@}.wasm
rm $top/client/gen/rask_wasm_${@}_bg.wasm
mv $top/client/gen/rask_wasm_${@}.js $top/client/gen/${@}.js
'''
]

[tasks.disassemble]
workspace = false
script = [
'''
#!/usr/bin/env bash -e
top=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ]; then
  echo "Not in a git repo!"
  exit 1
fi
wasm2wat --enable-threads -f --no-debug-names gen/${@}.wasm -o gen/${@}.wat --enable-bulk-memory
cargo run -p atomify gen/${@}.wat
'''
]
