kind: pipeline
name: default

steps:
- name: format
  image: truedoctor/rust-wasm:nightly-2020-02-28
  pull: if-not-exists
  commands:
  - nix-shell --run 'cargo make check-format' # check formatting for all projects
- name: build
  image: truedoctor/rust-wasm:nightly-2020-02-28
  pull: if-not-exists
  commands:
  - nix-shell --run 'cargo make all' # build all projects
- name: test
  image: truedoctor/rust-wasm:nightly-2020-02-28
  pull: if-not-exists
  commands:
  - nix-shell --run 'cargo make test' # test all projects

