extend = "./scripts/cargo-helpers.toml"

# component builds
[tasks.all]
dependencies = [ "backend", "frontend" ]
workspace = false

[tasks.frontend]
workspace = false
dependencies = [  ]
command = "cargo"
args = [ "make", "--cwd", "client/", "--makefile", "Makefile.toml", "all" ]

[tasks.backend]
workspace = false
dependencies = [ "rask-engine", "rask-server", "lobby" ]

# package builds
[tasks.rask-server]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "rask-server" ]

[tasks.rask-engine]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "rask-engine" ]


[tasks.lobby]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "lobby" ]

# dev tools
[tasks.serve-frontend]
command = "./scripts/dev-server"
workspace = false
args = [ "${@}" ]
dependencies = [ "frontend" ]

[tasks.serve-backend]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "run", "-p", "rask-server" ]

[tasks.cleanup]
workspace = false
dependencies = [ "clean" ]
script = [
  "rm -r $(git rev-parse --show-toplevel 2>/dev/null)/client/gen 2>/dev/null || true"
]

# upstream `ci-flow` task appears to have problems with wasm
[tasks.ci-flow]
workspace = false
dependencies = [ "cleanup", "all", "check-format", "test" ]

# watcher
[tasks.watch]
workspace = false
watch = true
command = "cargo"
args = [ "build", "-p ${@}" ]

# testierung
[tasks.test]
workspace = false
env = { CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all --exclude rask-wasm-logic --exclude rask-wasm-graphics --exclude rask-wasm-shared" }
