extend = "./scripts/cargo-helpers.toml"

[config]
additional_profiles = [ "watch" ]

# component builds
[tasks.all]
dependencies = [ "backend", "frontend", "lobby" ]
workspace = false

[tasks.frontend]
workspace = false
dependencies = [  ]
command = "cargo"
args = [ "make", "--cwd", "wasm/", "--makefile", "Makefile.toml", "all" , "--profile" , "dev"]

[tasks.backend]
workspace = false
dependencies = [ "rask-engine", "rask-server", "lobby" ]

# package builds
[tasks.rask-server]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "rask-server" ]

[tasks.rask-engine]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "rask-engine" ]

[tasks.lobby]
workspace = false
command = "cargo"
args = [ "make", "exec-${BUILD_ENV}", "--", "build", "-p", "lobby" ]

# dev tools
[tasks.serve]
workspace = false
watch = true
dependencies = [ "stop",  "backend", "lobby" ]
script = [ 
'''
cargo make serve-lobby &
#sleep 5 && ./scripts/dev-server &
cargo make serve-backend
''']

[tasks.stop]
workspace = false
watch = true
script = [ 
'''
#kill $(pgrep ./scripts/dev-server -f) 2>/dev/null || true
kill $(pgrep target/debug/lobby -f) 2>/dev/null || true
kill $(pgrep target/debug/rask-server -f) 2>/dev/null || true
''']

[tasks.serve-frontend]
command = "./scripts/dev-server"
workspace = false
args = [ "${@}" ]
watch = true
dependencies = [ "frontend" ]

[tasks.serve-backend]
workspace = false
command = "cargo"
watch = true
args = [ "make", "exec-${BUILD_ENV}", "--", "run", "-p", "rask-server" ]

[tasks.serve-lobby]
workspace = false
command = "cargo"
watch = true
args = [ "make", "exec-${BUILD_ENV}", "--", "run", "-p", "lobby" ]

[tasks.cleanup]
workspace = false
dependencies = [ "clean" ]
script = [
  "rm -r $(git rev-parse --show-toplevel 2>/dev/null)/client/gen 2>/dev/null || true"
]

# upstream `ci-flow` task appears to have problems with wasm
[tasks.ci-flow]
workspace = false
dependencies = [ "cleanup", "all", "check-format", "test" ]

# testierung
[tasks.test]
workspace = false
env = { CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = "--all --exclude rask-wasm" }
