[package]
name = "rask-wasm"
version = "0.1.0"
authors = ["natrixaeria", "Dennis Kobert <dennis@kobert.dev>"]
edition = "2018"
description = "WebAssembly frontend of the rask project"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
lazy_static = "1.4"

[dependencies.rask-engine]
version = "0.2.0"
path = "../rask-engine"
features = ["nightly"]

[dependencies.wee_alloc]
version = "=0.4.6"
features = ["size_classes", "static_ptr_backend"]
git = "https://github.com/squirrel-labs/wee_alloc/"
branch = "std-mutex"

[dependencies.parking_lot]
version = "0.10"
features = ["nightly"]
