extend = "../scripts/cargo-helpers.toml"

[tasks.all]
workspace = false
dependencies = [ "wasm" ]

[tasks.format]
workspace = false
command = "cargo"
args = [ "fmt", "--all" ]

[tasks.wasm]
workspace = false
env = { CARGO_TARGET_DIR = "../target/rask_wasm",  RUSTFLAGS = "-Ctarget-feature=+atomics,+bulk-memory -Clink-arg=--demangle" }
script = [
'''
#!/usr/bin/env bash -ex
top=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ]; then
  echo "Not in a git repo!"
  exit 1
fi
gen=$top/wasm/gen
cargo make exec-${BUILD_ENV} -- build -p rask-wasm --target wasm32-unknown-unknown -Z build-std=std,panic_abort
file=$top/target/rask_wasm/wasm32-unknown-unknown/${BUILD_ENV}/rask_wasm.wasm
wasm-dis $file -o $gen/client.wat
sed -i '/\s*(export "__heap_base" (global $global$[0-9]*))/i  (export "__sp" (global $global$0))' $gen/client.wat
wasm-as --enable-threads --enable-bulk-memory --enable-mutable-globals $gen/client.wat -o $gen/client.wasm -g -pa O@s
#wasm-opt --enable-threads --enable-bulk-memory --enable-mutable-globals $gen/client.wasm -o $gen/client.wasm -g -Os
'''
]
