extend = "../scripts/cargo-helpers.toml"

[tasks.all]
workspace = false
dependencies = [ "wasm" ]

[tasks.format]
workspace = false
command = "cargo"
args = [ "fmt", "--all" ]

[tasks.wasm]
workspace = false
env = { CARGO_TARGET_DIR = "../target/rask_wasm",  RUSTFLAGS = " -Ctarget-feature=+atomics,+bulk-memory" }
script = [
'''
#!/usr/bin/env bash -ex
top=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ]; then
  echo "Not in a git repo!"
  exit 1
fi
cargo make exec-${BUILD_ENV} -- build -p rask-wasm --target wasm32-unknown-unknown -Z build-std=std,panic_abort
file=$top/target/rask_wasm/wasm32-unknown-unknown/${BUILD_ENV}/rask_wasm.wasm
wasm-opt --enable-threads --enable-bulk-memory $file -o $top/wasm/gen/client.wasm
wasm2wat --enable-all -f $top/wasm/gen/client.wasm -o $top/wasm/gen/client.wat
'''
]
