[env]
BUILD_ENV = "debug"

[tasks.exec-debug]
command = "cargo"
toolchain = "nightly-2019-08-07"
args = [ "${@}" ]
workspace = false

[tasks.exec-release]
command = "cargo"
toolchain = "nightly-2019-08-07"
args = [ "${@}", "--release" ]
workspace = false
