[env.development]
BUILD_ENV = "debug"
[env.production]
BUILD_ENV = "release"

[tasks.exec-debug]
command = "cargo"
toolchain = "nightly-2020-02-28"
args = [ "${@}" ]
workspace = false

[tasks.exec-release]
command = "cargo"
toolchain = "nightly-2020-02-28"
args = [ "${@}", "--release" ]
workspace = false
