[env]
watch = "false"

[env.development]
BUILD_ENV = "debug"
CARGO_MAKE_DISABLE_WATCH = "true"
[env.production]
BUILD_ENV = "release"
CARGO_MAKE_DISABLE_WATCH = "true"
[env.watch]
BUILD_ENV = "debug"

[tasks.exec-debug]
command = "cargo"
toolchain = "nightly-2020-04-19"
args = [ "${@}" ]
workspace = false

[tasks.exec-release]
command = "cargo"
toolchain = "nightly-2020-04-19"
args = [ "${@}", "--release" ]
workspace = false
