[global.databases]
sqlite_db = {pool_size = 1, url = "db.sqlite" }
postgres = { url = "postgres://lobby@localhost/rask-lobby" }

[development]
address = "localhost"
port = 8000
#workers = [number of cpus * 2]
keep_alive = 5
log = "debug"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[staging]
address = "localhost"
port = 8008
#workers = [number of cpus * 2]
keep_alive = 5
log = "normal"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "localhost"
port = 8088
#workers = [number of cpus * 2]
keep_alive = 5
log = "normal"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }
