[package]
name = "rask-engine"
version = "0.2.0"
authors = ["konsumlamm <konsumlamm@gmail.com>", "Dennis Kobert <dennis@kobert.dev>"]
edition = "2018"

[dependencies]
image = "0.23"

[dependencies.spine_tiny]
git = "https://github.com/reeFridge/spine-rs"
