[package]
name = "rask-engine"
version = "0.2.0"
authors = ["konsumlamm <konsumlamm@gmail.com>", "Dennis Kobert <dennis@kobert.dev>"]
edition = "2018"

[dependencies.image]
version = "0.23"
default_features = false
features = ["png"]

[dependencies.spine_tiny]
git = "https://github.com/reeFridge/spine-rs"

[dev-dependencies]
lazy_static = "1.4.0"
